<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <TargetFrameworks>$(ApplicationTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <PackageTags>messagepack msgpack mvc-core formatter alphacloud</PackageTags>
    <Description>MessagePack formatters for ASP.NET Core MVC</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\common\AssemblyVersion.cs" Link="AssemblyVersion.cs" />
    <Compile Include="..\Alphacloud.MessagePack.HttpFormatter\Internal\SerializableTypesCache.cs" Link="SerializableTypesCache.cs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="JetBrains.Annotations" Version="2024.3.0" />
  </ItemGroup>

</Project>
